### ISSUE TITLE
Crash with JEI

### ISSUE THREAD

**Issue by mxnmnm** [eve0415/IFPatcher#2] opened 2021-12-07 06:22 UTC
Every time I click on the washing machine, fermentation station, or fluid sieving tab in JEI, I get this crash: https://gist.github.com/mxnmnm/9e15764c9aa5cbe1ce7763c9687f6710

If you need more info let me know

**Comment by eve0415** [comment] 2021-12-07 07:18
Not reproduceable.
![image](https://user-images.githubusercontent.com/40632436/144982464-392b2224-78dc-421e-889f-bdeb4d72513d.png)

If you have any way to reproduce the crash other than that, I'd like to know.

**Comment by mxnmnm** [comment] 2021-12-07 07:19
I can send you my pack to try it out, let me just upload it real quick

**Comment by mxnmnm** [comment] 2021-12-07 07:33
https://drive.google.com/file/d/1vwRZzKrz9hftkbqxKhJiPbbmD8nYHJM3/view?usp=sharing

**Comment by mxnmnm** [comment] 2021-12-07 07:33
Let me know if you need more info

**Comment by mxnmnm** [comment] 2021-12-08 06:45
I noticed optifine was kind of mentioned so I tested without optifine and I got a slightly different crash, but similar enough:
https://gist.github.com/mxnmnm/ab6dcd0470cffe01d6716978dafad9c9

**Comment by eve0415** [comment] 2022-01-03 15:30
Closing as this is not a bug from Industrial Foregoing. However thank you for reporting anyway.

**Closed as not planned by eve0415** 2022-01-03 15:30 UTC
Labels: wontfix
